### PR TITLE
become_loader is a member of ansible.plugins.loader

### PR DESCRIPTION
**Pull request by pguermo**

### CODE REVIEW

**Comment by pguermo** [comment]
@jlaska: has something changed in the configuration of the CI? I wonder this small change has broken the CI?

**Comment by pguermo** [comment]
@abadger Is something wrong now with the configuration of the project on Travis CI? I cannot understand how my commit may have broken that much the tests...

**Comment by kdelee** [comment]
Looks like the unit tests are busted, will look into it

**Comment by kdelee** [comment]
https://github.com/ansible/pytest-ansible/pull/41 fixed CI, think it has just been some drift in stdout + at least locally, the version of pytest I have needs these newer import paths

**Comment by kdelee** [comment]
@pguermo if you rebase, I think CI should pass and then once that passes I will merge

**Comment by pguermo** [comment]
@kdelee I've made the rebase, but CI is still complaining... ProtocolError: 'Connection broken' while collecting ansible

**Comment by kdelee** [comment]
@pguermo re-kicked failed job. Looks like local network flake on the test runner box to me

**Comment by kdelee** [comment]
Fixed!

Going to merge.

**Pull request merged**
