### PR TITLE
Fix duplicated host bug with extra_inventory

### PR DESCRIPTION
**Pull request by CFSNM**
The len and contains method in the module_dispatcher was not aware of the extra inventory, just of the inventory.

Fixes: #135

### CODE REVIEW

**Review by ssbarnea — DISMISSED** [review]
Please add a test or two for it to verify that the code works well.

**Review by Ruchip16 — COMMENTED** [review]
LGTM, @ssbarnea @cidrblock need your review once, also @CFSNM does this PR also address #135 issue?

**Comment by CFSNM** [comment]
thanks @Ruchip16, no, this PR is not addressing https://github.com/ansible/pytest-ansible/issues/135

**Comment by CFSNM** [comment]
The needed modifications to address https://github.com/ansible/pytest-ansible/issues/135 are quite related to the changes here, so using this PR to address it

**Review by Ruchip16 — APPROVED** [review]
LGTM, lets wait for @ssbarnea or @cidrblock review

**Comment by ssbarnea** [comment]
Please rebase it so we can merge it.

**Comment by CFSNM** [comment]
@ssbarnea done!

**Comment by ssbarnea** [comment]
I converted to draft until you add the tests, once all pipelines report green remove the draft and we will review and merge it. That helps us deal with pending reviews much easier.

**Comment by CFSNM** [comment]
@ssbarnea I was checking the covecov report, and all the uncovered lines are related to ansible-core versions prior to 2.13, and all these versions are EOL, should we removed the files related to them?

**Comment by CFSNM** [comment]
or even add some ansible versions in the premerge checks combinations, to test old ansible versions

**Comment by ssbarnea** [comment]
@cidrblock I need your input here. I am inlined to remove support for old pythons and ansible versions but I think that we had a reason why we had to keep compatibility with old versions only on this project. Do you remember the reasons?

**Comment by CFSNM** [comment]
@ssbarnea @cidrblock if you want to maintain old versions for legacy compatibility, we could consider moving to tox-ansible: https://github.com/ansible/tox-ansible this would allow us to generate custom testing envs with different python and ansible-core versions

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Please find a way to avoid reducing the code coverage, also rebase and squash you change in to single commit. 

PS. Nice work.

**Review by ssbarnea — APPROVED** [review]

**Comment by CFSNM** [comment]
pre-commit.ci autofix

**Pull request merged**
