### PR TITLE
Update tox.ini

### PR DESCRIPTION
**Pull request by geetikakay**
Adding changes in envlist based on python3.Ansible 2.5 and above has support for python3.
Refer : https://docs.ansible.com/ansible/2.5/reference_appendices/python_3_support.html

### CODE REVIEW

**Comment by jlaska** [comment]
@geetikakay Thanks!  Can you also update the `env` section in the `.travis.yml` file?  Otherwise, Travis CI won't run the desired environment.  

It also, if you look at Travis test results, it appears that the lint tests are failing on several lines in `errors.py`.  You can fix that in this PR, or I can fix in master and you'll need to rebase this PR.

**Comment by geetikakay** [comment]
@jlaska Hi James, Do you think we need to try with pip3?

**Comment by jlaska** [comment]
@geetikakay I pushed a fix for the `errors.py` lint issue, please rebase this PR.  I'm also pushing several related fixes to enable support for ansible-v25.  Thanks!

**Comment by jlaska** [comment]
I'm going to close this PR.  I've made a fair number of changes to fix tests, and update to newer versions of ansible.  I've also added python3.6 to the included travis and tox configurations.  3.6 tests are failing.  If anyone is willing to contribute PRs to fix those tests, I'd be happy!

**Pull request closed without merging**
