### PR TITLE
Provide BaseModuleDispatcher with iterator for hosts

### PR DESCRIPTION
**Pull request by jladdjr**

### CODE REVIEW

**Comment by jlaska** [comment]
@jladdjr can you rebase this PR?  I have a feeling it may not be needed anymore, but would be good to confirm.

**Comment by jladdjr** [comment]
@jlaska - sure, will get this rebased

**Comment by jlaska** [comment]
@jladdjr Is this still valid, or of interest?

**Comment by jladdjr** [comment]
@jlaska - don't know that we've been hurting to have this in lately. If this comes back up, can just open a new PR.

**Pull request closed without merging**
